baseURL = 'https://blog.dec22.kr/'
defaultContentLanguage = 'ko'
title = 'dec22'
theme = 'terminal'

[params]
  fullWidthTheme = false
  centerTheme = false
  contentTypeName = "posts"
  showMenuItems = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[module]
  [module.hugoVersion]
    extended = true
    max = ''
    min = '0.90.0'

[languages]
  [languages.ko]
    languageCode = 'ko-KR'
    title = 'dec22'

    [languages.ko.params]
      owner = 'ysk'

      [languages.ko.params.logo]
        logoText = 'dec22'

    [languages.ko.menu]
      [[languages.ko.menu.main]]
        identifier = "posts"
        name = "Post"
        url = "/posts"
      [[languages.ko.menu.main]]
        identifier = "notes"
        name = "Note"
        url = "/notes"
